routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\ItemController;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/category', CategoryController::class);
Route::resource('/item', ItemController::class);

// Ajax route
Route::post('/create-item', [ItemController::class, 'store']);
Route::put('/edit-item/{id}', [ItemController::class, 'update']);
Route::delete('/delete-item/{id}', [ItemController::class, 'destroy']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['category_id','category_name'];

    public function items()
    {
        return $this->hasMany(Item::class ,'category_id');
    }

    public $timestamp = false;

}

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $fillable = ['category_id','item_name'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('category.index' ,compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Category::create([
            'category_name' => $request->name,
        ]);
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id)->delete();
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Item;
use App\Models\Category;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::with(['category'])->get();
        $categories = Category::orderBy('category_name')->pluck('category_name','id');
        return view('item.index', compact('items','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $items  = Item::all();
        $categories = Category::orderBy('category_name')->pluck('category_name','id');
        return view('item.create' ,compact('items','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item = Item::create([
            'category_id'  => $request->category_id,
            'item_name'      => $request->item_name
        ]);
        return redirect()->route('item.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::orderBy('category_name')->pluck('id','category_name');
        $item = Item::findOrFail($id);
        return view('item.edit',compact('item','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = Item::findOrFail($id)->update([
            'category_id'   => $request->category_id,
            'item_name'     => $request->item_name
        ]);
        return redirect()->route('item.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::findOrFail($id)->delete();
        return redirect()->route('item.index');
    }
}

resources/views/Item/create.blade.php
@extends('master')

@section('content')

<h3> Create Item</h3>
    <form action="{{ route('item.store') }}" method="POST">
        @csrf
        <div>
            <label for="category"> Select Category : </label>
            <select name="category_id" id="category">
                @foreach ($categories as $id => $name)
                    <option value="{{ $id }}"> {{ $name }} </option>
                @endforeach
            </select>
        </div>
        <div>
            <label for="name"> Item Name : </label>
            <input type="text" name="item_name" id="name">
        </div>
        <div>
            <button type="submit"> Create </button>
        </div>
    </form>

@endsection

resources/views/Item/edit.blade.php
@extends('master')


@section('content')
    
<form action="{{ route('item.update', $item->id) }}" method="POST">
    @method('PUT')
    @csrf
    <div>
        <label for="category"> Select Category : </label>
        <select name="category_id" id="category">
            @foreach ($categories as $id => $name)
                <option selected={{ $item->category_id == $id}} value="{{ $id }}"> {{ $name }} </option>
            @endforeach
        </select>
    </div>
    <div>
        <label for="name"> Item Name : </label>
        <input type="text" name="item" id="name" value="{{ $item->item_name }}">
    </div>
    <div>
        <button type="submit"> Edit </button>
    </div>
</form>
    
@endsection

resources/views/Item/index.blade.php
@extends('master')

<style>


</style>

@section('content')

<table border=1px; text-align = center; margin-right="10px">
    <tr>
      <th>ID</th>
      <th>CategoryID</th>
      <th>Category</th>
      <th>Item</th>
      <th>Action</th>
    </tr>
    @foreach ($items as $item )
      <tr>
        <td>{{ $item->id}}</td>
        <td>{{ $item->category_id}}</td>
        <td>{{ $item->category->category_name}}</td>
        <td>{{ $item->item_name}}</td>
        <td>
          <a href="#" class="btn btn-success editbtn"> Edit </a>
        
            <button type="submit" class="btn btn-danger deletebtn"> Delete </button>
        </td>
      </tr>
    @endforeach
  </table>
  
  {{-- <!-- Add Item Modal --> --}}
  <div class="modal fade" id="createItemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <form action="{{ route('item.store') }}" method="POST" id="addform">
            <div class="modal-body">
                @method('POST')
                @csrf
                <div>
                    <label for="name"> Item Name : </label>
                    <input type="text" name="item_name" id="name">
                </div>
                <div>
                    <label for="category"> Select Category : </label>
                    <select name="category_id" id="category">
                        @foreach ($categories as $id => $name)
                            <option value="{{ $id }}"> {{ $name }} </option>
                        @endforeach
                    </select>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
          </form>
      </div>
    </div>
  </div>

  {{-- Edit Item Modal  --}}

  <div class="modal fade" id="editItemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit Item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="#" method="POST" id="editform">
          <div class="modal-body">
          @METHOD('PUT')
            @csrf
            <div>
              <input type="hidden" value="{{ $item->id }}" name="id" id="id">
            </div>
            <div>
              <div>
                <label for="category"> Select Category : </label>
                <select name="category_id" id="category_id" class="category_id">
                    @foreach ($categories as $id => $name)
                    ///isi tag option id karena kalau pake name get value ajax nya error
                      <option selected={{ $item->category_id == $id}} value="{{ $id }}"> {{ $id }} </option>
                    @endforeach
                </select>
              </div>
              <div>
                <label for="item"> Item Name : </label>
                <input type="text" name="item_name" id="item" value="{{ $item->item_name }}">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {{-- Delete Item Modal  --}}

  <div class="modal fade" id="deleteItemModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <form method="POST" name="deleteform" id="deleteItem">
            @method('DELETE')
            @csrf
            <div>
              <p>    Are you sure to delete item? </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-primary">Delete</button>
            </div>
          </form>
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createItemModal">
    Create Item
  </button>

  
@endsection

resources/views/category/create.blade.php
@extends('master')

@section('content')

<h3> Create Category</h3>
<fieldset>
    <form action="{{ route('category.store') }}" method="POST">
    @csrf
        <div>
            <label for="name"> Category Name : </label>
            <input type="text" name="name" id="name" reqeuired>
        </div>
        <button type="submit" name="submit"> Create </button>
    </form>
</fieldset>

@endsection

resources/views/category/index.blade.php
@extends('master')

{{-- <style>
    .name{
        display:flex;
        align-items: center;
        flex-direction: row;
    }
    .name form{
        margin-bottom: 0;
        margin-left: 10px;
    }
</style> --}}

@section('content')
<h3> List Category </h3>
    <table border=1px;>
        <tr>
            <td>Id</td>
            <td>Category Name</td>
            <td>Action</td>
        </tr>
        
        @foreach ($categories as $category)
            <tr>
                <td> {{ $category->id}} </td>
                <td> {{ $category->category_name}} </td>
                <td>
                    <form action="{{ route('category.destroy',$category->id ) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger"> Hapus </button>
                    </form>
                </td>
            </tr>
        @endforeach
        
    </table>

@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
    crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <header>
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <a href="{{ route('item.index')}}"> || Home || </a>
        <a href="{{ route('item.create')}}"> Create Item || </a>
        <a href="{{ route('category.index')}}"> List Category  ||</a>
        <a href="{{ route('category.create')}}"> Create Category || </a>
    </header>
    @yield('content')
    
    
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <script src="/js/ajax.js"></script>
    
</body>
</html>